node fix_admin_activities.cjs
node fix_admin_activities2.cjs
node fix_admin_registrations_link.cjs
node fix_admin_registrations_link2.cjs
node patch_admin_activities_tabs.cjs
node fix_admin_leave_email.cjs
node fix_admin_leave_email2.cjs
node fix_admin_leave_email3.cjs
node patch_admin_checkbox.cjs
node patch_images_upload.cjs
node patch_script_block.cjs
node fix_html_syntax.cjs
node fix_html_syntax2.cjs
node fix_newlines.cjs
node patch_alumni_admin.cjs
node patch_alumni_admin2.cjs
node patch_tabs.cjs
node patch_rank.cjs
