CREATE TABLE IF NOT EXISTS group_honors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  honor_name TEXT NOT NULL,
  year_label TEXT NOT NULL,
  tier INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
